export const data = [
    {
        "id": 1,
        "name": "Vinpearl Resort & Golf Phu Quoc",
        "category":"Romantic",
        "description": "Vinpearl Resort & Golf Phu Quoc is a luxurious resort located on Phu Quoc Island, known for its beautiful beaches and tropical landscapes. The resort offers world-class accommodation, an 18-hole golf course, and a range of recreational activities for guests to enjoy.",
        "nation": "Korea", 
        "director": "Yu Je-won",
        "actor": "Mark Hamill, Harrison Ford, Carrie Fisher",
        "duration": "16 tập ",
        "releaseDate": "2021",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/440913072.jpg?k=7499a374ecdae4abddbad2fe2c2a64a25e1d182e1fdd2ffe8ed708f6c5fef364&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/DsodZLGmpIQ"
    },
    {
        "id": 2,
        "name": "InterContinental Danang Sun Peninsula Resort",
        "category":"Romantic",
        "description": "Nestled on a hillside overlooking the East Sea, InterContinental Danang Sun Peninsula Resort offers breathtaking views and unparalleled luxury. With its award-winning design and world-class amenities, it's a top destination for travelers seeking an unforgettable experience.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Mark Hamill, Harrison Ford, Carrie Fisher",
        "duration": "16 tập",
        "releaseDate": "2021",
        "image": "https://duan-sungroup.com/wp-content/uploads/2022/12/intercontinental-da-nang-sun-peninsula-resort-la-du-an-nghi-duong-dang-cap-quoc-te.png",
        "trailer": "https://www.youtube.com/embed/bR5Il90f1vE"
    },

    {
        "id": 3,
        "name": "Six Senses Con Dao",
        "category":"Romantic",
        "description": "Six Senses Con Dao is a secluded paradise located on Con Dao archipelago. Surrounded by pristine beaches and lush tropical forests, the resort offers luxurious villas, holistic spa treatments, and a range of outdoor activities for guests to explore the natural beauty of Vietnam.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Mark Hamill, Harrison Ford, Carrie Fisher",
        "duration": "20 tập",
        "releaseDate": "2019",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/10974229.jpg?k=3e57728938f3f60078eb2a25dcd2bb24c1908775e60bbe8bfdbc66b0f44b3e9a&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/6tOxnroOTWU",
    },
    {
        "id": 4,
        "name": "Fusion Maia Resort Da Nang",
        "category":"Romantic",
        "description": "Fusion Maia Resort Da Nang is a wellness retreat set against the backdrop of Da Nang's stunning coastline. Guests can indulge in all-inclusive spa treatments, relax in private pool villas, and enjoy gourmet dining experiences inspired by Vietnamese cuisine.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Daisy Ridley, John Boyega, Oscar Isaac",
        "duration": "14 tập",
        "releaseDate": "2022",
        "image": "https://dulichkhampha24.com/wp-content/uploads/2020/07/Fusion-Maia-Resort-Da-Nang-ch.png",
        "trailer": "https://www.youtube.com/embed/lqU_kT4L0FQ",
    },
    {
        "id": 5,
        "name": "Amanoi",
        "category":"Romantic",
        "description": "Perched on a cliff overlooking Vinh Hy Bay, Amanoi offers guests a secluded paradise surrounded by pristine nature. With luxurious accommodations, personalized service, and breathtaking views, it's the perfect destination for discerning travelers seeking tranquility and relaxation.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Daisy Ridley, John Boyega, Mark Hamill",
        "duration": "16 tập",
        "releaseDate": "2016",
        "image": "https://www.americanexpress.com/en-us/travel/discover/photos/100508/60303/1200/Amanoi_Vietnam-Beach_Club.jpg",
        "trailer": "https://www.youtube.com/embed/tyhnEHCUtv4",
    },
    {
        "id": 6,
        "name": " Banyan Tree Lang Co ",
        "category":"Romantic",
        "description": "Situated between the East Sea and the Truong Son mountain range, Banyan Tree Lang Co offers guests a tranquil escape in the heart of nature. With luxurious villas, world-class amenities, and panoramic views, it's an ideal destination for romantic getaways and family vacations.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Daisy Ridley, John Boyega, Oscar Isaac",
        "duration": "16 tập",
        "releaseDate": "2016",
        "image": "https://www.banyantree.com/assets/2022-11/bt-langco-accommodation-seaviewhillpoolvilla-privatepool2.jpg",
        "trailer": "https://www.youtube.com/embed/-7OpOqzGEsA",
    },
    {
        "id": 7,
        "name": "JW Marriott Phu Quoc Emerald Bay Resort & Spa",
        "category":"Romantic",
        "description": "Inspired by the whimsical designs of 19th-century French colonial mansions, JW Marriott Phu Quoc offers guests a lavish retreat amidst lush gardens and pristine beaches. With its luxurious accommodations and world-class amenities, it's the perfect destination for luxury travelers seeking an unforgettable experience.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Ewan McGregor, Liam Neeson, Natalie Portman",
        "duration": "16 tập",
        "releaseDate": "2015",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484154580.jpg?k=ab8dd98c760c112ea2672d58c06be5a671b7de4b6c0f36b460dade0b12040337&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/zSOA2D-zdoo",
    },
    {
        "id": 8,
        "name": "Furama Resort Danang",
        "category":"Romantic",
        "description": "Set on the stunning Bac My An Beach, Furama Resort Danang offers guests a luxurious retreat with world-class amenities, fine dining options, and panoramic ocean views. With its pristine beaches and lush landscapes, it's an ideal destination for travelers seeking relaxation and adventure.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Ewan McGregor, Natalie Portman, Hayden Christensen",
        "duration": "16 tập",
        "releaseDate": "2019",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/64070859.jpg?k=f340e2ee68e6e898a6d9200ade7ba0ad27836a5591549e896d607243c16e6c51&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/awawSG3XBks",
    },
    {
        "id": 9,
        "name": "The Nam Hai Resort",
        "category":"Romantic",
        "description": "Renowned for its stunning architecture and pristine beachfront, The Nam Hai offers luxurious villas, exceptional service, and unparalleled views of the South China Sea. With its tranquil ambiance and world-class amenities, it's the perfect destination for luxury travelers seeking a serene retreat.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Ewan McGregor, Natalie Portman, Hayden Christensen",
        "duration": "16 tập",
        "releaseDate": "2017",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/76547733.jpg?k=7fbbe8a5086cba583ab13153aaf2d38202861f9ae74729622e44599b1440e5dc&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/DrcrRO4zYS0",
    },
    {
        "id": 10,
        "name": "Fusion Resort Cam Ranh",
        "category":"Romantic",
        "description": "Situated on the picturesque shores of Cam Ranh Bay, Fusion Resort Cam Ranh offers guests a luxurious retreat with panoramic ocean views and world-class amenities. With its all-inclusive spa treatments and gourmet dining experiences, it's the perfect destination for travelers seeking relaxation and rejuvenation.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "	Lee Hye Ri, Park Bo Gum, Ryu Jun Yeol, Go Kyung Pyo",
        "duration": "16 tập",
        "releaseDate": "2015",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/254296350.jpg?k=148a2523232ecab666998dd618942fb7caac0991b3cfff54d19e2f7395df5eb8&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/SV5jPHCMoJY",
    },
    {
        "id": 11,
        "name": "Premier Village Danang Resort",
        "category":"Romantic",
        "description": "Located on the pristine shores of My An Beach, Premier Village Danang Resort offers guests luxurious villas with private pools and stunning ocean views. With its world-class amenities and impeccable service, it's the perfect destination for travelers seeking luxury and relaxation.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Ewan McGregor, Natalie Portman, Hayden Christensen",
        "duration": "16 tập",
        "releaseDate": "2019",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/447996343.jpg?k=c87e782a01e08bd8e0aa244061f4518f7727ebf29da7428dbcf2b6a56a7891d9&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/PTrCwc1SKUo",
    },
    {
        "id": 12,
        "name": "Victoria Phan Thiet Beach Resort & Spa",
        "category":"Romantic",
        "description": "Nestled along the coastline of Phan Thiet, Victoria Phan Thiet Beach Resort & Spa offers guests a tranquil escape with lush gardens and stunning ocean views. With its luxurious accommodations and authentic Vietnamese hospitality, it's the perfect destination for travelers seeking relaxation and rejuvenation.",
        "nation": "Korea",
        "director": "Yu Je-won",
        "actor": "Ewan McGregor, Natalie Portman, Hayden Christensen",
        "duration": "16 tập",
        "releaseDate": "2022",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/136290539.jpg?k=e652f91bad1fcba0d939b0ac68d4a9b1a276ab5f4ab8bd4d2d7acddac5f59096&o=&hp=1",
        "trailer": "https://www.youtube.com/embed/oqxAJKy0ii4",
    },

]